image: node:18-alpine

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

variables:
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
  NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}

build:
  stage: build
  script:
    - npm install --legacy-peer-deps
    - npm run build
    - cp -r .next/static public/_next/static
  artifacts:
    paths:
      - public/
      - .next/
    expire_in: 1 week

pages:
  stage: deploy
  script:
    - cp -r public/* .
    - cp -r .next/static _next/static
  artifacts:
    paths:
      - .
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH 