image: node:18-alpine

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

variables:
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
  NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}

build:
  stage: build
  script:
    - npm install --legacy-peer-deps
    - npm run build
  artifacts:
    paths:
      - .next/
    expire_in: 1 week

test:
  stage: test
  script:
    - npm install --legacy-peer-deps
    - npm run test
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH 