image: node:18-alpine

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install --legacy-peer-deps
    - npm run build
  artifacts:
    paths:
      - .next/
      - public/
      - package.json
      - package-lock.json
    expire_in: 1 week

deploy:
  stage: deploy
  script:
    - npm install -g serve
    - serve -s .next -l 3000
  only:
    - main 